/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client.View;

import Client.Util.Session;
import Client.util.HandleRequest;
import Requests.LogoutRequest;
import Requests.*;
import Response.*;
import java.awt.EventQueue;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import jwt.JwtHelper;

/**
 *
 * @author vinic
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        showAdmin();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    HandleRequest.getInstance().getEchoSocket().close();
                } catch (IOException ex) {
                    
                }
            }
        });
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sidePanel = new javax.swing.JPanel();
        usuarioBtn = new javax.swing.JButton();
        pdiBtn = new javax.swing.JButton();
        segmentoBtn = new javax.swing.JButton();
        rotaBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        rotaView1 = new Client.View.RotaView();
        pdiView1 = new Client.View.PdiView();
        segmentoView1 = new Client.View.SegmentoView();
        usuarioView1 = new Client.View.UsuarioView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setLayout(new java.awt.GridBagLayout());

        usuarioBtn.setText("Usuario");
        usuarioBtn.setMaximumSize(new java.awt.Dimension(105, 22));
        usuarioBtn.setMinimumSize(new java.awt.Dimension(105, 22));
        usuarioBtn.setPreferredSize(new java.awt.Dimension(105, 22));
        usuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 7, 8);
        sidePanel.add(usuarioBtn, gridBagConstraints);

        pdiBtn.setText("PDI");
        pdiBtn.setMaximumSize(new java.awt.Dimension(105, 22));
        pdiBtn.setMinimumSize(new java.awt.Dimension(105, 22));
        pdiBtn.setPreferredSize(new java.awt.Dimension(105, 22));
        pdiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdiBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 7, 8);
        sidePanel.add(pdiBtn, gridBagConstraints);

        segmentoBtn.setText("Segmento");
        segmentoBtn.setMaximumSize(new java.awt.Dimension(105, 22));
        segmentoBtn.setMinimumSize(new java.awt.Dimension(105, 22));
        segmentoBtn.setPreferredSize(new java.awt.Dimension(105, 22));
        segmentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segmentoBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 7, 8);
        sidePanel.add(segmentoBtn, gridBagConstraints);

        rotaBtn.setText("Rota");
        rotaBtn.setMaximumSize(new java.awt.Dimension(105, 22));
        rotaBtn.setMinimumSize(new java.awt.Dimension(105, 22));
        rotaBtn.setPreferredSize(new java.awt.Dimension(105, 22));
        rotaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotaBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 7, 8);
        sidePanel.add(rotaBtn, gridBagConstraints);

        logoutBtn.setText("Logout");
        logoutBtn.setMaximumSize(new java.awt.Dimension(105, 22));
        logoutBtn.setMinimumSize(new java.awt.Dimension(105, 22));
        logoutBtn.setPreferredSize(new java.awt.Dimension(105, 22));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 7, 8);
        sidePanel.add(logoutBtn, gridBagConstraints);

        getContentPane().add(sidePanel, java.awt.BorderLayout.LINE_START);

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(rotaView1, "card2");
        mainPanel.add(pdiView1, "card4");
        mainPanel.add(segmentoView1, "card4");
        mainPanel.add(usuarioView1, "card5");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void segmentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segmentoBtnActionPerformed
        mainPanel.removeAll();
        segmentoView1 = new SegmentoView();
        mainPanel.add(segmentoView1);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_segmentoBtnActionPerformed

    private void rotaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotaBtnActionPerformed
        mainPanel.removeAll();
        rotaView1 = new RotaView();
        mainPanel.add(rotaView1);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_rotaBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        JFrame cur = this;
        EventQueue.invokeLater(() -> {
            HandleRequest.getInstance().makeRequest(new LogoutRequest(Session.getInstance().getToken()), (Response <?> res) -> {
                LoginView login = new LoginView();
                login.setVisible(true);
                cur.dispose();
            }, null);
        });
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void usuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBtnActionPerformed
        mainPanel.removeAll();
        usuarioView1 = new UsuarioView();
        mainPanel.add(usuarioView1);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_usuarioBtnActionPerformed

    private void pdiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdiBtnActionPerformed
        mainPanel.removeAll();
        pdiView1 = new PdiView();
        mainPanel.add(pdiView1);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_pdiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton pdiBtn;
    private Client.View.PdiView pdiView1;
    private javax.swing.JButton rotaBtn;
    private Client.View.RotaView rotaView1;
    private javax.swing.JButton segmentoBtn;
    private Client.View.SegmentoView segmentoView1;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton usuarioBtn;
    private Client.View.UsuarioView usuarioView1;
    // End of variables declaration//GEN-END:variables
    
    private void showAdmin(){
        if(!(JwtHelper.getAdminStatus(Session.getInstance().getToken()))){
            segmentoBtn.setVisible(false);
            pdiBtn.setVisible(false);
        }
    }
}
